"""Typed request and response models for NS.Gifts API v2."""

from .requests import (
    CreateOrderRequest,
    ExchangeRateRequest,
    JSONScalar,
    OrderField,
    OrderReference,
    PayOrderRequest,
    RequestModel,
    SteamUserRequest,
    TokenRequest,
)
from .responses import (
    BalanceResponse,
    CreateOrderResponse,
    ExchangeRateResponse,
    ExchangeRates,
    OrderInfoResponse,
    PaymentResponse,
    ResponseModel,
    SteamApp,
    SteamAppsResponse,
    SteamUserResponse,
    StockCategory,
    StockFieldSchema,
    StockResponse,
    StockService,
    TokenResponse,
)

__all__ = [
    "BalanceResponse",
    "CreateOrderRequest",
    "CreateOrderResponse",
    "ExchangeRateRequest",
    "ExchangeRateResponse",
    "ExchangeRates",
    "JSONScalar",
    "OrderField",
    "OrderInfoResponse",
    "OrderReference",
    "PayOrderRequest",
    "PaymentResponse",
    "RequestModel",
    "ResponseModel",
    "SteamApp",
    "SteamAppsResponse",
    "SteamUserRequest",
    "SteamUserResponse",
    "StockCategory",
    "StockFieldSchema",
    "StockResponse",
    "StockService",
    "TokenRequest",
    "TokenResponse",
]
